Repository hugodias360/devops-aula07, pull requests merged in 2018-03, with the labels that each got.

#2 Create requisitos.md
  docs/requisitos.md
Labels: análise

#4 Create arquitetura.md
  docs/arquitetura.md
Labels: arquitetura

#6 Create jogovelha.py
  src/jogovelha.py
Labels: • programação

#13 Create analise
  docs/analise
Labels: análise

#15 Create arquitetura_funcionalidade.md
  docs/arquitetura_funcionalidade.md
Labels: arquitetura

#17 Create efetuar_uma_jogada.py
  src/efetuar_uma_jogada.py
Labels: • programação

#19 Create teste_jogada.py
  src/teste_jogada.py
Labels: testes

#20 V1.0
  docs/analise
  docs/arquitetura_funcionalidade.md
  src/efetuar_uma_jogada.py
  src/teste_jogada.py
Labels: operações
